title: Erika Lisco
# logo:
# description: text below image
#show_downloads: false
theme: jekyll-theme-minimal

nav:
  - title: "Home"
    url: "/"
  - title: "Professional"
    url: "/professional/"
  - title: "Academic"
    url: "/academic/"
  - title: "For Fun"
    url: "/fun/"
